### PR TITLE
Project: Social Media Website

### PR DESCRIPTION
**Pull request by krys2fa**
# Milestone 8: Deploy app to heroku

This pull request references pull request #5 

- we fixed all issues raised in pull request #5 by @kobiyoyo.

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Progress @team :clap: Almost there :checkered_flag: However, some features need to be implemented in order to get approval for this milestone. Check :arrow_down: 

* [ ] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
  - There is no button or links to reject a friendship request
* [ ] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by SafaErden** [comment]
Hi, @stratospherique, your pathwright link is broken about rejection, can you send us the functional link, thank you.

**Comment by krys2fa** [comment]
Hi @stratospherique, we have implemented the requested changes.
Thanks.

**Review by stratospherique — APPROVED** [review]
### Great work implementing the suggested changes :clap: :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

**Comment by krys2fa** [comment]
Thanks for the approval @stratospherique 😃

**Pull request merged**
